name: Test
on: [push, workflow_dispatch]
jobs:
  test-fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: v-gowridurgad/setup-node@fix-1628
        with:
          node-version-file: "test.json"
      
      - name: Check version
        run: |
          node -v

  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@main
        with:
          node-version-file: "test.json"
      
      - name: Check version
        run: |
          node -v