name: Test
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version-file: "project1/package.json"
          cache-dependency-path: "project1/package-lock.json"
      
      - name: Check version
        run: |
          node -v
          echo "${PWD}"