name: Test
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: v-gowridurgad/setup-node@fix-1628
        with:
          node-version-file: "package.json"
      
      - name: Check version
        run: |
          node -v
          
